/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadFileRouteImport } from './routes/_authenticated/upload-file'
import { Route as AuthenticatedTypeFileRouteImport } from './routes/_authenticated/type-file'
import { Route as AuthenticatedTempRouteRouteImport } from './routes/_authenticated/temp-route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadFileRoute = AuthenticatedUploadFileRouteImport.update({
  id: '/upload-file',
  path: '/upload-file',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTypeFileRoute = AuthenticatedTypeFileRouteImport.update({
  id: '/type-file',
  path: '/type-file',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTempRouteRoute = AuthenticatedTempRouteRouteImport.update({
  id: '/temp-route',
  path: '/temp-route',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/temp-route': typeof AuthenticatedTempRouteRoute
  '/type-file': typeof AuthenticatedTypeFileRoute
  '/upload-file': typeof AuthenticatedUploadFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/temp-route': typeof AuthenticatedTempRouteRoute
  '/type-file': typeof AuthenticatedTypeFileRoute
  '/upload-file': typeof AuthenticatedUploadFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/temp-route': typeof AuthenticatedTempRouteRoute
  '/_authenticated/type-file': typeof AuthenticatedTypeFileRoute
  '/_authenticated/upload-file': typeof AuthenticatedUploadFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/docs'
    | '/dashboard'
    | '/temp-route'
    | '/type-file'
    | '/upload-file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/dashboard'
    | '/temp-route'
    | '/type-file'
    | '/upload-file'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/docs'
    | '/_authenticated/dashboard'
    | '/_authenticated/temp-route'
    | '/_authenticated/type-file'
    | '/_authenticated/upload-file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload-file': {
      id: '/_authenticated/upload-file'
      path: '/upload-file'
      fullPath: '/upload-file'
      preLoaderRoute: typeof AuthenticatedUploadFileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/type-file': {
      id: '/_authenticated/type-file'
      path: '/type-file'
      fullPath: '/type-file'
      preLoaderRoute: typeof AuthenticatedTypeFileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/temp-route': {
      id: '/_authenticated/temp-route'
      path: '/temp-route'
      fullPath: '/temp-route'
      preLoaderRoute: typeof AuthenticatedTempRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTempRouteRoute: typeof AuthenticatedTempRouteRoute
  AuthenticatedTypeFileRoute: typeof AuthenticatedTypeFileRoute
  AuthenticatedUploadFileRoute: typeof AuthenticatedUploadFileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTempRouteRoute: AuthenticatedTempRouteRoute,
  AuthenticatedTypeFileRoute: AuthenticatedTypeFileRoute,
  AuthenticatedUploadFileRoute: AuthenticatedUploadFileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
